image:
  repository: 043902793725.dkr.ecr.ap-southeast-1.amazonaws.com/paymentservice
  tag: latest
imagePullSecrets:
- name: ecr-credentials
deployments:
- name: paymentservice
  replicasCount: 1
  prometheusEnabled: true
  istioEnabled: true  
  service:
    name: paymentservice
    # HTTPPort: 50050
    gRPCPort: 50050
    healthType: grpc
    health:
      livenessPort: 50050
      readinessPort: 50050
      initialDelaySeconds: 20
      periodSeconds: 10
      failureThreshold: 5
      timeoutSeconds: 3
env:
  PORT: 50050
  DISABLE_PROFILER: 1
port: 50050
resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"
infisical:
  enabled: false
istio:
  enabled: true
  destinationRule:
    enabled: true
    host: paymentservice
    trafficPolicy: 
      outlierDetection:
        consecutive5xxErrors: 5
        interval: 30s              
        baseEjectionTime: 30s       
        maxEjectionPercent: 30
        minHealthPercent: 70      
  authorizationPolicy:
    enabled: true
    action: ALLOW
    rules:
    - from:
      - source:
          principals: [
            "cluster.local/ns/online-boutique/sa/checkoutservice"
          ] 
      to:
      - operation:
          ports: ["10000"]