helm:
  parameters:
  - name: image.name
    value: 043902793725.dkr.ecr.ap-southeast-1.amazonaws.com/productcatalogservice
    forcestring: true
  - name: image.tag
    value: 0b3073d7-dev
    forcestring: true
