helm:
  parameters:
  - name: image.name
    value: 043902793725.dkr.ecr.ap-southeast-1.amazonaws.com/shippingservice
    forcestring: true
  - name: image.tag
    value: 2ec5fcdd-dev
    forcestring: true
