helm:
  parameters:
  - name: image.name
    value: 043902793725.dkr.ecr.ap-southeast-1.amazonaws.com/checkoutservice
    forcestring: true
  - name: image.tag
    value: 1631ac0a-dev
    forcestring: true
