helm:
  parameters:
  - name: image.name
    value: 043902793725.dkr.ecr.ap-southeast-1.amazonaws.com/currencyservice
    forcestring: true
  - name: image.tag
    value: a02759aa-dev
    forcestring: true
