helm:
  parameters:
  - name: image.name
    value: 043902793725.dkr.ecr.ap-southeast-1.amazonaws.com/recommendationservice
    forcestring: true
  - name: image.tag
    value: 3b717c71-dev
    forcestring: true
