helm:
  parameters:
  - name: image.name
    value: 043902793725.dkr.ecr.ap-southeast-1.amazonaws.com/paymentservice
    forcestring: true
  - name: image.tag
    value: 4bb37ceb-dev
    forcestring: true
