helm:
  parameters:
  - name: image.name
    value: 043902793725.dkr.ecr.ap-southeast-1.amazonaws.com/recommendationservice
    forcestring: true
  - name: image.tag
    value: 772c04d2-dev
    forcestring: true
