{{- if .Values.secretProviderClass.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProviderClass.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  provider: {{ .Values.secretProviderClass.provider }} # e.g., "azure", "aws", "vault"
  parameters:
    {{- toYaml .Values.secretProviderClass.parameters | nindent 4 }}
  {{- if .Values.secretProviderClass.secretObjects }}
  secretObjects:
    {{- toYaml .Values.secretProviderClass.secretObjects | nindent 4 }}
  {{- end }}
{{- end }}
