{{- if .Values.istio.enabled }}
{{- if .Values.istio.destinationRule.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "gea.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gea.labels" . | nindent 4 }}
spec:
  host: {{ .Values.istio.destinationRule.host | default (include "gea.fullname" .) }}
  {{- if .Values.istio.destinationRule.subsets }}
  subsets:
    {{- range .Values.istio.destinationRule.subsets }}
  - name: {{ .name }}
    labels:
      {{- toYaml .labels | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- if .Values.istio.destinationRule.trafficPolicy }}
  trafficPolicy:
    {{- toYaml .Values.istio.destinationRule.trafficPolicy | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}