{{- if .Values.istio.enabled }}
{{- if .Values.istio.rateLimiting.enabled }}
{{- if .Values.istio.rateLimiting.local.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: {{ include "gea.fullname" . }}-ratelimit
  labels:
    {{- include "gea.labels" . | nindent 4 }}
spec:
  workloadSelector:
    labels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        portNumber: {{ .Values.container.port }}
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.local_ratelimit
        typed_config:
          "@type": type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
          value:
            stat_prefix: http_local_rate_limiter
            token_bucket:
              max_tokens: {{ .Values.istio.rateLimiting.local.tokenBucket.maxTokens }}
              tokens_per_fill: {{ .Values.istio.rateLimiting.local.tokenBucket.tokensPerFill }}
              fill_interval: {{ .Values.istio.rateLimiting.local.tokenBucket.fillInterval }}
            filter_enabled:
              runtime_key: local_rate_limit_enabled
              default_value:
                numerator: 100
                denominator: HUNDRED
            filter_enforced:
              runtime_key: local_rate_limit_enforced
              default_value:
                numerator: 100
                denominator: HUNDRED
            response_headers_to_add:
            - append: false
              header:
                key: x-local-rate-limit
                value: 'true'
{{- end }}
{{- end }}
{{- end }}