{{- if .Values.istio.enabled }}
{{- if .Values.istio.virtualService.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "gea.fullname" . }}
  labels:
    {{- include "gea.labels" . | nindent 4 }}
spec:
  hosts:
    {{- toYaml .Values.istio.virtualService.hosts | nindent 4 }}
  gateways:
    {{- if .Values.istio.virtualService.gateways }}
    {{- toYaml .Values.istio.virtualService.gateways | nindent 4 }}
    {{- else if .Values.istio.gateway.enabled }}
    - {{ .Values.istio.gateway.name | default (printf "%s-gateway" (include "gea.fullname" .)) }}
    {{- end }}
  http:
    {{- range .Values.istio.virtualService.http }}
    - match:
        {{- toYaml .match | nindent 8 }}
      route:
        {{- range .route }}
        - destination:
            host: {{ .destination.host | default (include "gea.fullname" $) }}
            {{- if .destination.port }}
            port:
              number: {{ .destination.port.number | default $.Values.service.port }}
            {{- end }}
            {{- if .destination.subset }}
            subset: {{ .destination.subset }}
            {{- end }}
          weight: {{ .weight | default 100 }}
        {{- end }}
      {{- with .retries }}
      retries:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .timeout }}
      timeout: {{ . }}
      {{- end }}
      {{- with .fault }}
      fault:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .corsPolicy }}
      corsPolicy:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end }}
{{- end }}